name: chelnok_mob
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.9+9

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  ###############################
  # localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # state management
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  flutter_bounceable: ^1.2.0
  sign_in_with_apple: ^6.1.4
  flutter_signin_button: ^2.0.0
  # json
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0    
  riverpod_annotation: ^2.6.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  #Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.2 
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.3
  gap: ^3.0.1
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  cached_network_image: ^3.4.1
  device_info_plus: ^11.1.1
  android_id: ^0.4.0
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  expandable_text: ^2.3.0
  collection: ^1.18.0
  mask_text_input_formatter: ^2.9.0
  wolt_modal_sheet: ^0.9.4
  # flutter_web_auth: ^0.6.0
  package_info_plus: ^8.1.3
  ###############################




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ##############################
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  flutter_launcher_icons: ^0.14.3



flutter_icons:
  image_path: "assets/images/app_icon.png"  
  android: true
  remove_alpha_ios: true 
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
